meta_product_name: "Pickalgo"
meta_title: "Devenez testeur de promo !"
meta_description: "Aidez les produits qui vous plaisent à adopter le meilleur prix promotionnel. Profitez en retour de la meilleure promo négociée pour vous."
meta_image: "tags.jpg"                           # Une image dans votre dossier app/assets/images/
