meta_product_name: "Pickalgo"
meta_title: "Devenez testeur de promos !"
meta_description: "Parce qu'il est difficile pour un vendeur de trouver le meilleur prix pour sa promo, il y a Pickalgo... et vous ! Avec Pickalgo devenez testeur de promos et bénéficiez du meilleur prix avant tout le monde."
meta_image: "tags.jpg"                           # Une image dans votre dossier app/assets/images/
